package com.amn.courses.controllers;

import com.amn.courses.dto.UserRepository;
import com.amn.courses.grpc.GrpcClient;
import com.amn.courses.misc.JWTUtil;
import com.amn.courses.models.User;
import net.minidev.json.JSONObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.Optional;

@Controller
@RequestMapping(path = "/user")
public class UserController {

    private JWTUtil jwtUtil = new JWTUtil();

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @PostMapping(path="", produces= MediaType.APPLICATION_JSON_VALUE) // Map ONLY POST Requests
    public @ResponseBody ResponseEntity<Object> addNewUser (@RequestBody User user) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        for (User u : userRepository.findAll()) {
            if(u.getUsername().equals(user.getUsername())){
                JSONObject entity = new JSONObject();
                entity.put("message","No double usernames");
                GrpcClient.log("User", "Create", "Fail");
                return new ResponseEntity<Object>(entity,HttpStatus.BAD_REQUEST);
            }
        }

        userRepository.save(user);
        JSONObject entity = new JSONObject();
        entity.put("message","Saved");
        GrpcClient.log("User", "Create", "Success");
        return new ResponseEntity<Object>(entity,HttpStatus.OK);
    }

    @GetMapping(path="")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        GrpcClient.log("User", "Get all", "Success");
        return userRepository.findAll();
    }


    @GetMapping(path="{id}", produces= MediaType.APPLICATION_JSON_VALUE)
    public @ResponseBody ResponseEntity<Object> getUser(@PathVariable(value="id") Integer id) {
        // This returns a JSON or XML with the users
        Optional<User> user = userRepository.findById(id);
        if(user.isEmpty()) {
            JSONObject entity = new JSONObject();
            entity.put("message","Not Found");
            GrpcClient.log("User", "Get single", "Fail");
            return new ResponseEntity<Object>(entity,HttpStatus.NOT_FOUND);
        }
        else {
            GrpcClient.log("User", "Get single", "Success");
            return ResponseEntity.ok(user);
        }
    }

    @DeleteMapping(path="/{id}", produces= MediaType.APPLICATION_JSON_VALUE)
    public @ResponseBody ResponseEntity<Object> deleteUser(@PathVariable(value="id") Integer id) {
        userRepository.deleteById(id);
        JSONObject entity = new JSONObject();
        entity.put("message","Deleted");
        GrpcClient.log("User", "Delete", "Success");
        return new ResponseEntity<Object>(entity,HttpStatus.OK);
    }

    @PostMapping(path = "/login", produces= MediaType.APPLICATION_JSON_VALUE)
    public @ResponseBody ResponseEntity<Object> login(@RequestBody User user){
        Iterable<User> users = userRepository.findAll();
        for (User u: users) {
            if(u.getUsername().equals(user.getUsername())){
                if(u.getPassword().equals(user.getPassword())){
                    JSONObject entity = new JSONObject();
                    entity.put("token",jwtUtil.generateToken(u));
                    entity.put("user", u);
                    GrpcClient.log("User", "Login", "Success");
                    return ResponseEntity.ok(entity);
                } else {
                    break;
                }
            }
        }

        JSONObject entity = new JSONObject();
        entity.put("message","Wrong username/password combination");
        GrpcClient.log("User", "Login", "Fail");
        return new ResponseEntity<Object>(entity,HttpStatus.BAD_REQUEST);
    }

    @PostMapping(path="/register", produces= MediaType.APPLICATION_JSON_VALUE) // Map ONLY POST Requests
    public @ResponseBody ResponseEntity<Object> registerNewUser (@RequestBody User user) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        for (User u : userRepository.findAll()) {
            if(u.getUsername().equals(user.getUsername())){
                JSONObject entity = new JSONObject();
                entity.put("message","No double usernames");
                GrpcClient.log("User", "Register", "Fail");
                return new ResponseEntity<Object>(entity,HttpStatus.BAD_REQUEST);
            }
        }

        userRepository.save(user);
        JSONObject entity = new JSONObject();
        entity.put("message","Saved");
        GrpcClient.log("User", "Register", "Success");
        return new ResponseEntity<Object>(entity,HttpStatus.OK);
    }
}
